### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#147]
Read/test through the files, check when completed

Readme:
- [x] Code
  - [x] Code/scripts
  - [x] Code/functions
  - [x] Code/graphing
- [x] Paper (all)
- [x] Paper/section **need readme(?)**
- [x] Data (all)
- [x] project-theta (main) See #150 

Running make
- [x] Code
  - [x] Code/scripts
- [x] Paper (all)
- [x] Data (all)
- [x] project-theta (main)
- [x] slides **Important too**

Paper Draft read through: how are we deciding to build this? if we do it my sections, we need a readme for the sections directory as well
- [x] read paper for spelling and grammar
- [x] merge into master

Address issues:
- [x] #107 
- [x] #138 
- [x] #139 
- [x] #141 
- [x] #105

**Comment by BenjaminHsieh** [comment]
@changsiyao @boyinggong @brianqiu @pigriver123

**Comment by briankleinqiu** [comment]
Why do we need a makefile for code/functions? Also why slides important

**Comment by briankleinqiu** [comment]
Ok at 7:00 pm if no word on the final paper I'll pull in boyings and update the makefile/readme for paper

**Comment by BenjaminHsieh** [comment]
@brianqiu your right, deleted the functions checkbox, 
we should just check that the slides can be built too

**Comment by BenjaminHsieh** [comment]
So we are building the paper from only 1 large text?

**Comment by boyinggong** [comment]
Yes

**Comment by BenjaminHsieh** [comment]
ok we can delete the sections then
also, are all the figures in paper/figures?

**Comment by boyinggong** [comment]
yes, I think so. Can you also make it on your computer to double check this? thanks

**Comment by BenjaminHsieh** [comment]
have to fix readme and makefile in paper, doing this right now, can everyone start going through the checklist and comment on what they are going to do? thanks

**Comment by briankleinqiu** [comment]
I'm proofreading paper

**Comment by changsiyao** [comment]
I tried all the codes except for mixed effect and bncorrelate, all those that I tried work fine.

**Comment by boyinggong** [comment]
Please modify it directly if there were any problems with the phrase and spelling. @brianqiu thanks.

**Comment by BenjaminHsieh** [comment]
@brianqiu merge my paper updates first

**Comment by briankleinqiu** [comment]
done

**Comment by briankleinqiu** [comment]
Merge to master? IS IT TIME

**Comment by BenjaminHsieh** [comment]
We dont have the paperfig command!!

**Comment by BenjaminHsieh** [comment]
We dont have enough time to do this, lets just merge the version we have now

**Comment by briankleinqiu** [comment]
Im deleting mentions of paperfig in code. Where else are they

**Comment by BenjaminHsieh** [comment]
code makefile, readme and main readme

**Comment by briankleinqiu** [comment]
cant find in main

**Comment by briankleinqiu** [comment]
yeahhh merged dev into master now. 0 seconds to spare lol

**Comment by BenjaminHsieh** [comment]
gg

**Comment by boyinggong** [comment]
Finally! Done!

**Comment by changsiyao** [comment]
Thanks guys! Sorry couldn't be more helpful tonight~ great working with you guys!

**Comment by BenjaminHsieh** [comment]
yep yep same here

**Comment by BenjaminHsieh** [comment]
closing

**Comment by BenjaminHsieh** [comment]
Guys I just realized our paper will not build if Ross runs make all from
main project directory BC of make paperfig, we need to delete the make
paperfig command in the readme and makefile

**Comment by changsiyao** [comment]
Yeah, we should. I wonder if it's too late...
It seems like paperfig is mentioned in code/Makefile, project_theta/Makefile and project_theta README.
or could we update some of the figures that we can (not many since Boying maded most of them on her computer and printed screen...)
